export const previewLocations = [
  {
    id: "preview-utrecht",
    name: "Xin Chao Utrecht",
    slug: "utrecht",
    address: "Voor Clarenburg 6, 3511 JE Utrecht",
    phone: "+31 30 123 4567",
    email: "hello@xinchao.nl",
    openTime: "12:00",
    closeTime: "21:00",
    openingHours: [
      { day: "monday", hours: "12:00-21:00" },
      { day: "tuesday", hours: "12:00-21:00" },
      { day: "wednesday", hours: "12:00-21:00" },
      { day: "thursday", hours: "12:00-21:00" },
      { day: "friday", hours: "12:00-21:00" },
      { day: "saturday", hours: "12:00-21:00" },
      { day: "sunday", hours: "12:00-21:00" },
    ],
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "preview-wageningen",
    name: "Xin Chao Wageningen",
    slug: "wageningen",
    address: "Hoogstraat 18, 6701 BT Wageningen",
    phone: "+31 317 765 4321",
    email: "hello@xinchao.nl",
    openTime: "12:00",
    closeTime: "20:00",
    openingHours: [
      { day: "monday", hours: "12:00-20:00" },
      { day: "tuesday", hours: "12:00-20:00" },
      { day: "wednesday", hours: "12:00-20:00" },
      { day: "thursday", hours: "12:00-20:00" },
      { day: "friday", hours: "12:00-20:00" },
      { day: "saturday", hours: "12:00-20:00" },
      { day: "sunday", hours: "12:00-20:00" },
    ],
    createdAt: new Date("2026-01-02T00:00:00.000Z"),
  },
];

export const previewDietaryOptions = [
  { slug: "vegan", nameEn: "Vegan", nameNl: "Veganistisch", sortOrder: 1 },
  { slug: "vegetarian", nameEn: "Vegetarian", nameNl: "Vegetarisch", sortOrder: 2 },
  { slug: "gluten-free", nameEn: "Gluten-Free", nameNl: "Glutenvrij", sortOrder: 3 },
  { slug: "dairy-free", nameEn: "Dairy-Free", nameNl: "Zuivelvrij", sortOrder: 4 },
];

export const previewMenuCategories = [
  {
    id: "preview-pho",
    name: "Pho",
    slug: "pho",
    sortOrder: 1,
    items: [
      {
        id: "preview-pho-bo",
        name: "Pho Bo",
        nameNl: "Pho Bo",
        shortDescription: "Beef noodle soup with fresh herbs",
        shortDescriptionNl: "Rundernoedelsoep met verse kruiden",
        description: "Traditional beef noodle soup with herbs",
        descriptionNl: "Traditionele rundernoedelsoep met kruiden",
        price: 1395,
        salePrice: null,
        taxClass: "standard",
        imageUrl: "/images/hero-pho.jpg",
        imageUrls: [],
        isAvailable: true,
        isDineInOnly: false,
        sortOrder: 1,
        dietaryTags: ["dairy-free"],
        isSpicy: false,
      },
      {
        id: "preview-pho-ga",
        name: "Pho Ga",
        nameNl: "Pho Ga",
        shortDescription: "Chicken noodle soup with lime and basil",
        shortDescriptionNl: "Kippennoedelsoep met limoen en basilicum",
        description: "Chicken noodle soup with fresh herbs",
        descriptionNl: "Kippennoedelsoep met verse kruiden",
        price: 1295,
        salePrice: null,
        taxClass: "standard",
        imageUrl: "/images/hero-pho.jpg",
        imageUrls: [],
        isAvailable: true,
        isDineInOnly: false,
        sortOrder: 2,
        dietaryTags: ["dairy-free", "gluten-free"],
        isSpicy: false,
      },
    ],
  },
  {
    id: "preview-bun",
    name: "Bun",
    slug: "bun",
    sortOrder: 2,
    items: [
      {
        id: "preview-bun-cha",
        name: "Bun Cha",
        nameNl: "Bun Cha",
        shortDescription: "Grilled pork with vermicelli noodles",
        shortDescriptionNl: "Gegrild varkensvlees met rijstvermicelli",
        description: "Grilled pork with vermicelli noodles",
        descriptionNl: "Gegrild varkensvlees met rijstvermicelli",
        price: 1495,
        salePrice: null,
        taxClass: "standard",
        imageUrl: "/images/hero-pho.jpg",
        imageUrls: [],
        isAvailable: true,
        isDineInOnly: false,
        sortOrder: 1,
        dietaryTags: ["dairy-free"],
        isSpicy: true,
      },
    ],
  },
  {
    id: "preview-drinks",
    name: "Drinks",
    slug: "drinks",
    sortOrder: 3,
    items: [
      {
        id: "preview-tra-da",
        name: "Tra Da",
        nameNl: "Vietnamese ijsthee",
        shortDescription: "Iced tea with lemongrass",
        shortDescriptionNl: "IJsthee met citroengras",
        description: "Vietnamese iced tea",
        descriptionNl: "Vietnamese ijsthee",
        price: 295,
        salePrice: null,
        taxClass: "standard",
        imageUrl: "/images/hero-pho.jpg",
        imageUrls: [],
        isAvailable: true,
        isDineInOnly: false,
        sortOrder: 1,
        dietaryTags: ["vegan"],
        isSpicy: false,
      },
    ],
  },
];
